networks:
  default:
    name: media
    external: true

services:

  # https://hub.docker.com/r/qmcgaw/gluetun
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    environment: #https://github.com/qdm12/gluetun-wiki/blob/main/setup/providers/mullvad.md
      - VPN_SERVICE_PROVIDER=$VPNPROVIDER
      - OPENVPN_USER=$GTUSER
    volumes:
      - ./gluetun/config.toml:/gluetun/auth/config.toml
    ports:
    #the container port(s) should be the ones needed for the container you want to use the gluetun network
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
      - 8000:8000 #for API access in homepage
    restart: unless-stopped
      
  # https://hub.docker.com/r/linuxserver/qbittorrent
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - WEBUI_PORT=8080
    volumes:
      - ./qbit:/config
      - $MEDIADIR:/media
    network_mode: service:gluetun
    restart: unless-stopped
    
  # https://hub.docker.com/r/linuxserver/bazarr
  bazarr:
    image: ghcr.io/linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - ./bazarr:/config
      - $MEDIADIR:/media #needs to match Radarr and Sonar path to have same directory access
    ports:
      - 6767:6767
    restart: unless-stopped

  # https://hub.docker.com/r/hotio/plex
  plex:
    container_name: plex
    image: cr.hotio.dev/hotio/plex
    restart: unless-stopped
    logging:
      driver: json-file
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - UMASK=002
      - DEBUG=no
      - PLEX_CLAIM=$PLEX_CLAIM
      - PLEX_PASS=$PLEX_PASS
      - ADVERTISE_IP=$PLEX_ADVERTISE_IP
    volumes:
      - ./plex:/config:rw
      - $PLEXMEDIA:/data/media:rw
      - /tmp:/transcode:rw
    ports: #required for bridge network mode
      - 32400:32400
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    devices:
      - /dev/dri:/dev/dri #required for Synology users
      
    # host network doesn't work for Docker Desktop on Windows,
    # use bridge network mode instead,with 'media' network:
    # https://docs.linuxserver.io/images/docker-plex/#optional-parameters  
    
    # network_mode: host
    
  # https://hub.docker.com/r/linuxserver/prowlarr
  prowlarr:
    image: ghcr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - ./prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  # https://hub.docker.com/r/linuxserver/radarr
  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - UMASK=022
    volumes:
      - ./radarr:/config
      - $MEDIADIR:/media
    ports:
      - 7878:7878
    restart: unless-stopped

  # https://hub.docker.com/r/linuxserver/sonarr
  sonarr:
    image: ghcr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - UMASK=022
    volumes:
      - ./sonarr:/config
      - $MEDIADIR:/media
    ports:
      - 8989:8989
    restart: unless-stopped
