services:

  # https://hub.docker.com/r/qmcgaw/gluetun
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports: # the container port(s) should be the ones needed for the container you want to use the gluetun network
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
      - 8000:8000 #for API access in homepage
    volumes:
      - ${CONFIG}:/gluetun/auth/config.toml
    restart: unless-stopped
    environment: # https://github.com/qdm12/gluetun-wiki/blob/main/setup/providers/mullvad.md
      - VPN_SERVICE_PROVIDER=${VPNPROVIDER}
      - OPENVPN_USER=${GTUSER}
      
  # https://hub.docker.com/r/linuxserver/qbittorrent
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    volumes:
      - qbittorrent:/config
      - ${MEDIADIR}/torrents:/downloads
    network_mode: service:gluetun
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8080
    
  # https://hub.docker.com/r/linuxserver/bazarr
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    ports:
      - 6767:6767
    volumes:
      - bazarr:/config
      - $MEDIADIR/libraries:/data/libraries #needs to match Radarr and Sonar path to have same directory access
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

  # https://hub.docker.com/r/linuxserver/prowlarr
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    ports:
      - 9696:9696
    volumes:
      - prowlarr:/config
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

  # https://hub.docker.com/r/linuxserver/radarr
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    ports:
      - 7878:7878
    volumes:
      - radarr:/config
      - ${MEDIADIR}:/data
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=022

  # https://hub.docker.com/r/linuxserver/sonarr
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    ports:
      - 8989:8989
    volumes:
      - sonarr:/config
      - ${MEDIADIR}:/data
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=022


volumes:
  qbittorrent:
  bazarr:
  prowlarr:
  radarr:
  sonarr:
  recyclarr:


  # # https://hub.docker.com/r/hotio/plex
  # plex:
  #   container_name: plex
  #   image: cr.hotio.dev/hotio/plex
  #   restart: unless-stopped
  #   logging:
  #     driver: json-file
  #   environment:
  #     - PUID=$PUID
  #     - PGID=$PGID
  #     - TZ=$TZ
  #     - UMASK=002
  #     - DEBUG=no
  #     - PLEX_CLAIM=$PLEX_CLAIM
  #     - PLEX_PASS=$PLEX_PASS
  #     - ADVERTISE_IP=$PLEX_ADVERTISE_IP
  #   volumes:
  #     - ./plex:/config:rw
  #     - $PLEXMEDIA:/data/media:rw
  #     - /tmp:/transcode:rw
  #   ports: #required for bridge network mode
  #     - 32400:32400
  #     - 32410:32410/udp
  #     - 32412:32412/udp
  #     - 32413:32413/udp
  #     - 32414:32414/udp
  #   devices:
  #     - /dev/dri:/dev/dri #required for Synology users
      
  #   # host network doesn't work for Docker Desktop on Windows,
  #   # use bridge network mode instead,with 'media' network:
  #   # https://docs.linuxserver.io/images/docker-plex/#optional-parameters  
    
  #   # network_mode: host
