# https://github.com/hoarder-app/hoarder/blob/main/docker/docker-compose.yml
services:
  web:
    container_name: hoarder-web
    image: ghcr.io/hoarder-app/hoarder:${HOARDER_VERSION:-release}
    ports:
      - 3001:3000
    volumes:
      - data:/data
    restart: unless-stopped
    environment:
      - DATA_DIR=${DATA_DIR}
      - BROWSER_WEB_URL=${BROWSER_WEB_URL}
      - MEILI_ADDR=${MEILI_ADDR}
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - CRAWLER_VIDEO_DOWNLOAD=${CRAWLER_VIDEO_DOWNLOAD}
      - CRAWLER_VIDEO_DOWNLOAD_MAX_SIZE=-1

  chrome:
    container_name: hoarder-chrome
    image: gcr.io/zenika-hub/alpine-chrome:123
    restart: unless-stopped
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars

  meilisearch:
    container_name: hoarder-meilisearch
    image: getmeili/meilisearch:v1.11.1
    volumes:
      - meilisearch:/meili_data
    restart: unless-stopped
    environment:
      - MEILI_NO_ANALYTICS=${MEILI_NO_ANALYTICS}
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}

volumes:
    meilisearch:
    data:
