# https://github.com/hoarder-app/hoarder/blob/main/docker/docker-compose.yml
services:
  web:
    container_name: hoarder-web
    image: ghcr.io/hoarder-app/hoarder:${HOARDER_VERSION:-release}
    restart: unless-stopped
    volumes:
      - data:/data
    ports:
      - 3001:3000
    env_file:
      - hoarder.env
    environment:
      MEILI_ADDR: http://meilisearch:7700
      BROWSER_WEB_URL: http://chrome:9222
      DATA_DIR: /data

  chrome:
    container_name: hoarder-chrome
    image: gcr.io/zenika-hub/alpine-chrome:123
    restart: unless-stopped
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars

  meilisearch:
    container_name: hoarder-meilisearch
    image: getmeili/meilisearch:v1.6
    restart: unless-stopped
    env_file:
      - hoarder.env
    environment:
      MEILI_NO_ANALYTICS: "true"
    volumes:
      - meilisearch:/meili_data

volumes:
    meilisearch:
    data:
