# https://docs.linuxserver.io/images/docker-code-server/
# https://coder.com/docs/code-server/install#docker
services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    ports:
      - 8443:8443
    volumes:
      - config:/config
      - /root:/local
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - PASSWORD=${PASSWORD}
      - TZ=${TZ}
      - DEFAULT_WORKSPACE=${DEFAULT_WORKSPACE} #optional
    #command:
    #  - --disable-telemetry

volumes:
  config:
