# https://docs.linuxserver.io/images/docker-code-server/
services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      #- PUID=1000
      #- PGID=1000
      - TZ=America/New_York
      - DEFAULT_WORKSPACE=~/docker #optional
    volumes:
      - config:/config
    ports:
      - 8443:8443
    restart: unless-stopped

volumes:
  config:
