# https://github.com/laurent22/joplin/tree/dev/packages/server
services:
  db:
    image: postgres:16
    container_name: joplin-db
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DATABASE}
  app:
    image: joplin/server:latest
    container_name: joplin-app
    depends_on:
      - db
    ports:
      - 22300:22300
    restart: unless-stopped
    environment:
      - APP_PORT=${APP_PORT}
      - APP_BASE_URL=${APP_BASE_URL}
      - DB_CLIENT=${DB_CLIENT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

volumes:
  data:
