# https://hub.docker.com/r/containrrr/watchtower
services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8081:8080 #for homepage API access
    restart: unless-stopped
