# https://docs.linuxserver.io/images/docker-jellyfin/
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    ports:
      - 8096:8096
      - 7359:7359/udp # Optional - Allows clients to discover Jellyfin on the local network.
      - 1900:1900/udp # Optional - Service discovery used by DNLA and clients.
    volumes:
      - ${CONFIG}:/config
      - ${LIBRARIES}:/libraries
    restart: unless-stopped
    devices:
      - /dev/dri:/dev/dri
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - JELLYFIN_PublishedServerUrl=${PUBLISHEDSERVERURL} # Optional - autodiscovery response domain or IP address
