# https://jellyfin.org/docs/general/installation/container#docker
# https://jellyfin.org/docs/general/administration/hardware-acceleration/intel#configure-with-linux-virtualization
# setup is a little buggy for me, try adding a server and ignore the login screen afterwards,
# and instead try going to http://ipaddress:8096 until the setup screen appears
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    network_mode: 'host'
    volumes:
      - config:/config
      - cache:/cache
      - ${LIBRARIES}:/libraries
    restart: 'unless-stopped'
    environment:
      - JELLYFIN_PublishedServerUrl=${PUBLISHEDSERVERURL} # optional - alternative address used for autodiscovery
    extra_hosts:
      - 'host.docker.internal:host-gateway' # optional - may be necessary for docker healthcheck to pass if running in host network mode
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128 # transcoding - must be first passed through Proxmox to VM
    group_add:
      - "105" # transcoding - check with: getent group render | cut -d: -f3

volumes:
  config:
  cache:
